# Use uma imagem leve do Nginx como base
FROM nginx:alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /usr/share/nginx/html

# Copie os arquivos do projeto para o diretório de trabalho
COPY . .

# Exponha a porta 80 para o tráfego externo
EXPOSE 80
